{{- if $.Values.dataGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "data-generator-{{ include "dataplatform-chart.fullname" . }}"
  labels:
    app.kubernetes.io/component: data-generator
    {{- include "dataplatform-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: data-generator
      {{- include "dataplatform-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: data-generator
        {{- include "dataplatform-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: data-generator
          image: "{{ $.Values.dataGenerator.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: WEATHER_STATION_MAX_ID
              value: "{{ $.Values.dataGenerator.stationMaxId }}"
            - name: WEATHER_STATION_TOPIC
              value: "{{ $.Values.dataGenerator.stationTopic }}"
            - name: WEATHER_STATION_INTERVAL
              value: "{{ $.Values.dataGenerator.stationInterval }}"
            - name: KAFKA_BOOTSTRAP_HOST
              value: kafka-cluster-{{ include "dataplatform-chart.fullname" . }}-kafka-bootstrap.{{ $.Release.Namespace }}.svc.cluster.local
            - name: CLICKHOUSE_HOST
              value: clickhouse-clickhouse-{{ include "dataplatform-chart.fullname" . }}.{{ $.Release.Namespace }}.svc.cluster.local
            - name: CLICKHOUSE_USERNAME
              value: "{{ $.Values.clickhouse.username }}"
            - name: CLICKHOUSE_PASSWORD
              value: "{{ $.Values.clickhouse.password }}"
            - name: POSTGRES_HOST_R
              value: postgres-cluster-{{ include "dataplatform-chart.fullname" . }}-r.{{ $.Release.Namespace }}.svc.cluster.local
            - name: POSTGRES_HOST_RW
              value: postgres-cluster-{{ include "dataplatform-chart.fullname" . }}-rw.{{ $.Release.Namespace }}.svc.cluster.local
            - name: POSTGRES_HOST_RO
              value: postgres-cluster-{{ include "dataplatform-chart.fullname" . }}-ro.{{ $.Release.Namespace }}.svc.cluster.local
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef: 
                  name: postgres-cluster-{{ include "dataplatform-chart.fullname" . }}-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: postgres-cluster-{{ include "dataplatform-chart.fullname" . }}-app
                  key: password
      restartPolicy: Always
{{- end }}